version: '3.9'
services:
  rpc-server:
    build: rpc-server
    ports:
      - "8888:8888"
    environment:
      - SERVICE_NAME=rpc-server
      - SERVICE_TAGS=rpc
    depends_on:
      - etcd
      - redis-server
#    volumes:
#      - type: bind
#        source: ./rpc-server
#        target: /app
  http-server:
    build: http-server
    ports:
      - "8080:8080"
    environment:
      - SERVICE_NAME=http-server
      - SERVICE_TAGS=http
    depends_on:
      - etcd
      - rpc-server
      - redis-server
  redis-server:
    image: redis
    ports:
      - "6379:6379"
  etcd:
    image: quay.io/coreos/etcd:v3.5.0
    command: ["etcd", "--advertise-client-urls", "http://etcd:2379", "--listen-client-urls", "http://0.0.0.0:2379"]
    ports:
      - "2379:2379"
